import { redirect } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import WorkspaceShell from '@/components/WorkspaceShell';

export default async function Customers(){
 const {supabase,user,profile}=await requireUser(); if(!user||!profile) redirect('/login'); const org=profile.organization_id;
 const {data:customers}=await supabase.from('customers').select('*').eq('organization_id',org).order('total_spend',{ascending:false}).limit(300);
 const ids=(customers??[]).map((c:any)=>c.id); let recentOrders:any[]=[]; if(ids.length){const r=await supabase.from('connected_orders').select('id,customer_id,channel,total_amount,currency,status,ordered_at').in('customer_id',ids).order('ordered_at',{ascending:false}).limit(500);recentOrders=r.data??[];}
 const orderMap=new Map<string,any[]>(); for(const o of recentOrders){const arr=orderMap.get(o.customer_id)||[];arr.push(o);orderMap.set(o.customer_id,arr)}
 const spend=(customers??[]).reduce((s:number,c:any)=>s+Number(c.total_spend||0),0); const repeat=(customers??[]).filter((c:any)=>['repeat','vip'].includes(c.lifecycle)).length;
 return <WorkspaceShell title="Customers" subtitle="One customer identity across connected sites and sales channels" profile={profile}><section className="page-heading"><div><div className="eyebrow">Customer 360</div><h1>Customers</h1><p>Unify purchases, WhatsApp enquiries and connected-store activity around the same customer record.</p></div><div className="metric-chip"><strong>{customers?.length??0}</strong><span>known customers</span></div></section><section className="metric-grid"><div className="metric-card"><span>Known customers</span><strong>{customers?.length??0}</strong></div><div className="metric-card"><span>Repeat / VIP</span><strong>{repeat}</strong></div><div className="metric-card"><span>Tracked customer spend</span><strong>₦{spend.toLocaleString()}</strong></div><div className="metric-card"><span>Recent linked orders</span><strong>{recentOrders.length}</strong></div></section><section className="customer-grid">{(customers??[]).map((c:any)=>{const orders=orderMap.get(c.id)||[];return <article key={c.id} className="app-card customer-card"><div className="flex items-start justify-between gap-3"><div><h3>{c.name||c.phone||c.email||'Unnamed customer'}</h3><p>{c.phone||c.email||'No contact details'}</p></div><span className="status-pill">{c.lifecycle}</span></div><div className="customer-stats"><div><span>Orders</span><strong>{c.total_orders}</strong></div><div><span>Spend</span><strong>₦{Number(c.total_spend||0).toLocaleString()}</strong></div></div><div className="customer-meta"><span>{c.primary_source||'unknown source'}</span><span>{c.last_order_at?`Last order ${new Date(c.last_order_at).toLocaleDateString()}`:'No order yet'}</span></div>{orders[0]&&<div className="customer-last-order"><span>{orders[0].channel||'store'}</span><strong>{orders[0].currency||'NGN'} {Number(orders[0].total_amount||0).toLocaleString()}</strong></div>}</article>})}{!customers?.length&&<div className="empty-dropzone">Customer records will appear as connected stores, WhatsApp and sales channels send identity-bearing events.</div>}</section></WorkspaceShell>
}
