import {redirect} from 'next/navigation';import {requireUser} from '@/lib/auth';import WorkspaceShell from '@/components/WorkspaceShell';import BuyerIntentQuickCreate from '@/components/BuyerIntentQuickCreate';import BuyerIntentActions from '@/components/BuyerIntentActions';
function money(v:any){return v?`₦${Number(v).toLocaleString()}`:'—'}
export default async function Buyers(){const {supabase,user,profile}=await requireUser();if(!user||!profile)redirect('/login');const {data:intents}=await supabase.from('buyer_intents').select('*,assignee:profiles!buyer_intents_assigned_to_fkey(full_name)').eq('organization_id',profile.organization_id).neq('status','ignored').order('intent_score',{ascending:false}).order('observed_at',{ascending:false}).limit(250);const rows=intents??[];const enugu=rows.filter((x:any)=>`${x.city||''} ${x.state||''}`.toLowerCase().includes('enugu')).length;const hot=rows.filter((x:any)=>Number(x.intent_score)>=70&&['new','qualified','matched','contacting'].includes(x.status)).length;const opted=rows.filter((x:any)=>x.consent_status==='opted_in').length;
 return <WorkspaceShell title="Buyer Intelligence" subtitle="Find demand, match products and route sales work" profile={profile}>
  <section className="page-heading"><div><div className="eyebrow">Demand capture</div><h1>Buyer Intelligence</h1><p>Capture consented leads and public demand signals from Enugu and across Nigeria, then match them against GadgetPoint-owned product mirrors without duplicating store administration.</p></div></section>
  <section className="grid gap-3 md:grid-cols-3"><div className="app-card p-5"><div className="text-3xl font-bold">{hot}</div><div className="text-sm text-slate-500">high-intent opportunities</div></div><div className="app-card p-5"><div className="text-3xl font-bold">{enugu}</div><div className="text-sm text-slate-500">Enugu demand signals</div></div><div className="app-card p-5"><div className="text-3xl font-bold">{opted}</div><div className="text-sm text-slate-500">buyers opted in for contact</div></div></section>
  <section className="app-card mt-6 p-5"><h2 className="section-title">Capture demand</h2><p className="mb-4 text-sm text-slate-500">Use this for WhatsApp enquiries, walk-ins, campaign responses and supported marketplace enquiries. Public signals can be recorded for aggregate demand intelligence, but direct outreach stays disabled unless the buyer opted in.</p><BuyerIntentQuickCreate/></section>
  <section className="mt-6 space-y-4">{rows.map((x:any)=>{const matches=Array.isArray(x.matched_products)?x.matched_products:[];return <article key={x.id} className="app-card p-5"><div className="grid gap-5 xl:grid-cols-[1fr_340px]"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{x.product_query}</h2><span className="source-pill">{x.source}</span><span className="rounded-full border px-2.5 py-1 text-xs font-semibold">Score {Number(x.intent_score).toFixed(0)}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs capitalize">{x.status}</span></div><div className="mt-2 text-sm text-slate-600">{[x.buyer_name,x.city,x.state].filter(Boolean).join(' · ')||'Location not supplied'} · Budget {money(x.budget_max)} · {x.urgency} urgency</div><div className="mt-2 text-xs text-slate-500">Consent: {x.consent_status.replaceAll('_',' ')} {x.assignee?.full_name?`· Assigned to ${x.assignee.full_name}`:''}</div><div className="mt-4"><BuyerIntentActions id={x.id} leadId={x.lead_id} canContact={x.consent_status==='opted_in'}/></div></div><div><div className="text-xs font-semibold uppercase tracking-wider text-slate-500">Best product matches</div><div className="mt-2 space-y-2">{matches.slice(0,3).map((m:any)=><div key={m.id||m.external_product_id} className="rounded-2xl border p-3"><div className="font-medium">{m.name}</div><div className="text-xs text-slate-500">{m.category||'Product'} · {money(m.price)} · stock {Number(m.stock_quantity||0)}</div></div>)}{!matches.length&&<div className="rounded-2xl border border-dashed p-4 text-sm text-slate-500">No matching connected product yet.</div>}</div></div></div></article>})}{!rows.length&&<div className="rounded-3xl border border-dashed p-10 text-center text-slate-500">No buyer demand captured yet.</div>}</section>
 </WorkspaceShell>}
