import Link from 'next/link';
import { redirect } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import WorkspaceShell from '@/components/WorkspaceShell';

export default async function Today(){
 const {supabase,user,profile}=await requireUser(); if(!user||!profile) redirect('/login'); const org=profile.organization_id; const now=new Date(); const iso=now.toISOString(); const soon=new Date(now.getTime()+24*60*60*1000).toISOString();
 const [recs,tasks,leads,approvals,orders,signals,sites]=await Promise.all([
  supabase.from('growth_recommendations').select('id,title,rationale,score,recommendation_type').eq('organization_id',org).eq('status','new').order('score',{ascending:false}).limit(6),
  supabase.from('tasks').select('id,title,status,priority,due_at').eq('organization_id',org).not('status','in','("completed","approved","cancelled")').lte('due_at',soon).order('due_at',{ascending:true}).limit(8),
  supabase.from('leads').select('id,name,source,product_interest,next_followup_at,status').eq('organization_id',org).not('status','in','("purchased","lost")').lte('next_followup_at',soon).order('next_followup_at',{ascending:true}).limit(8),
  supabase.from('approvals').select('id,entity_type,created_at,status').eq('organization_id',org).eq('status','pending').order('created_at',{ascending:true}).limit(6),
  supabase.from('connected_orders').select('id,external_order_id,total_amount,currency,channel,status,ordered_at').eq('organization_id',org).order('ordered_at',{ascending:false}).limit(5),
  supabase.from('commerce_signals').select('id,source,signal_type,product_ref,search_query,value,observed_at').eq('organization_id',org).order('observed_at',{ascending:false}).limit(8),
  supabase.from('connected_sites').select('id,name,domain,status').eq('organization_id',org).order('created_at',{ascending:true})
 ]);
 const overdue=(tasks.data??[]).filter((t:any)=>t.due_at&&new Date(t.due_at)<now).length;
 const dueLeads=(leads.data??[]).filter((l:any)=>l.next_followup_at&&new Date(l.next_followup_at)<=now).length;
 const metrics=[['Priority recommendations',recs.data?.length??0,'/opportunities'],['Overdue tasks',overdue,'/tasks'],['Follow-ups due',dueLeads,'/leads'],['Approvals waiting',approvals.data?.length??0,'/approvals']];
 return <WorkspaceShell title="Today" subtitle="Your daily operating brief" profile={profile}><div className="mx-auto max-w-7xl px-6 py-8">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm font-semibold uppercase tracking-[.2em] text-slate-500">Daily command center</div><h1 className="mt-2 text-3xl font-bold">What should we do today?</h1><p className="mt-2 max-w-2xl text-slate-600">WorkflowOS combines staff work, customer follow-up, connected commerce and growth signals into one operating view.</p></div><div className="rounded-2xl border bg-white px-4 py-3 text-sm"><span className="font-semibold">{sites.data?.length??0}</span> connected site{sites.data?.length===1?'':'s'}</div></div>
  <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label,value,href]:any)=><Link href={href} key={label} className="rounded-3xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div><div className="mt-2 text-xs font-semibold text-slate-500">Open →</div></Link>)}</section>
  <section className="mt-7 grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
   <div className="space-y-6"><div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Best growth moves</h2><Link href="/opportunities" className="text-sm font-semibold">Opportunity Center →</Link></div><div className="mt-4 space-y-3">{(recs.data??[]).map((r:any)=><div key={r.id} className="flex gap-4 rounded-2xl border p-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-slate-900 font-bold text-white">{Math.round(Number(r.score||0))}</div><div><div className="font-semibold">{r.title}</div><div className="mt-1 text-sm text-slate-500">{r.rationale||'WorkflowOS found a growth action worth reviewing.'}</div><div className="mt-2 text-xs font-semibold uppercase tracking-wide text-slate-400">{r.recommendation_type}</div></div></div>)}{!recs.data?.length&&<div className="rounded-2xl border border-dashed p-6 text-sm text-slate-500">No recommendations are waiting. New storefront, marketplace and sales signals will appear here.</div>}</div></div>
   <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Recent connected commerce</h2><Link href="/analytics" className="text-sm font-semibold">Analytics →</Link></div><div className="mt-4 space-y-3">{(orders.data??[]).map((o:any)=><div key={o.id} className="flex items-center justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div><div className="font-medium">Order {o.external_order_id}</div><div className="text-sm text-slate-500">{o.channel||'connected store'} · {o.status}</div></div><div className="font-bold">{o.currency||'NGN'} {Number(o.total_amount||0).toLocaleString()}</div></div>)}{!orders.data?.length&&<div className="text-sm text-slate-500">No connected orders yet.</div>}</div></div></div>
   <div className="space-y-6"><div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Execution queue</h2><div className="mt-4 space-y-3">{(tasks.data??[]).slice(0,5).map((t:any)=><Link href="/tasks" key={t.id} className="block rounded-2xl border p-4"><div className="flex items-center justify-between gap-3"><span className="font-medium">{t.title}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{t.priority}</span></div><div className="mt-2 text-xs text-slate-500">{t.due_at?`${new Date(t.due_at)<now?'Overdue · ':''}${new Date(t.due_at).toLocaleString()}`:'No due date'}</div></Link>)}{!tasks.data?.length&&<div className="text-sm text-slate-500">No tasks due in the next 24 hours.</div>}</div></div>
   <div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Customer follow-ups</h2><div className="mt-4 space-y-3">{(leads.data??[]).slice(0,5).map((l:any)=><Link href="/leads" key={l.id} className="block rounded-2xl border p-4"><div className="font-medium">{l.name||'Unnamed lead'}</div><div className="mt-1 text-sm text-slate-500">{l.product_interest||'General inquiry'} · {l.source||'unknown source'}</div><div className="mt-2 text-xs font-semibold text-slate-500">{l.next_followup_at?new Date(l.next_followup_at).toLocaleString():'Follow-up not scheduled'}</div></Link>)}{!leads.data?.length&&<div className="text-sm text-slate-500">No customer follow-ups due in the next 24 hours.</div>}</div></div>
   <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Demand radar</h2><Link href="/analytics" className="text-sm font-semibold">See signals →</Link></div><div className="mt-4 flex flex-wrap gap-2">{(signals.data??[]).map((s:any)=><span key={s.id} className="rounded-full border bg-white px-3 py-2 text-xs"><strong>{s.source}</strong> · {s.search_query||s.product_ref||s.signal_type}</span>)}{!signals.data?.length&&<span className="text-sm text-slate-500">No commerce signals yet.</span>}</div></div></div>
  </section>
 </div></WorkspaceShell>
}
