'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

type Offer={id:string;title:string;source_price:number|null;selling_price:number|null;availability:string|null;source_url?:string|null;metadata?:any;vendor?:{name?:string|null;status?:string|null}|null};
type Vendor={id:string;name:string;status:string|null};

export default function BuyerSourcingPanel({intentId,productQuery,canContact,offers,vendors,quoteId}:{intentId:string;productQuery:string;canContact:boolean;offers:Offer[];vendors:Vendor[];quoteId?:string|null}){
 const router=useRouter(); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy('offer');setMessage('');const fd=new FormData(e.currentTarget);const payload={intent_id:intentId,action:'add_offer',title:fd.get('title'),vendor_id:fd.get('vendor_id')||null,supplier_name:fd.get('supplier_name')||null,source_url:fd.get('source_url')||null,source_price:Number(fd.get('source_price')||0),selling_price:Number(fd.get('selling_price')||0),availability:fd.get('availability')||'available',notes:fd.get('notes')||null};const r=await fetch('/api/buyer-intents/sourcing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({}));setBusy('');if(!r.ok){setMessage(b.error||'Could not save sourcing option.');return;}e.currentTarget.reset();setMessage('Sourcing option saved.');router.refresh();}
 async function quote(offerId:string){setBusy(`quote:${offerId}`);setMessage('');const r=await fetch('/api/buyer-intents/sourcing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent_id:intentId,action:'create_quote',offer_id:offerId})});const b=await r.json().catch(()=>({}));setBusy('');if(!r.ok){setMessage(b.error||'Could not create quote.');return;}setMessage('Quotation prepared.');router.refresh();}
 return <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50/60 p-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[0.14em] text-slate-400">Sourcing & pricing</div><div className="mt-1 text-sm font-black text-slate-900">Find the product, protect the margin, prepare the quote</div></div>{quoteId&&<Link href="/quotes" className="rounded-lg bg-[#2377ff] px-3 py-2 text-xs font-bold text-white">Open quotation →</Link>}</div>
  <div className="mt-4 space-y-2">{offers.map((offer)=>{const cost=Number(offer.source_price||0),sell=Number(offer.selling_price||0),profit=sell-cost,margin=sell>0?(profit/sell)*100:0;return <div key={offer.id} className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-bold text-slate-900">{offer.title}</div><div className="mt-1 text-xs text-slate-500">{offer.vendor?.name||offer.metadata?.supplier_name||'Unverified source'} · {offer.availability||'availability unknown'}</div></div><div className="text-right text-xs"><div className="font-black text-slate-900">Sell ₦{sell.toLocaleString()}</div><div className="mt-1 text-slate-500">Cost ₦{cost.toLocaleString()} · Profit ₦{profit.toLocaleString()} · {margin.toFixed(1)}%</div></div></div><div className="mt-3 flex flex-wrap gap-2">{offer.source_url&&<a href={offer.source_url} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700">Open source ↗</a>}{!quoteId&&<button disabled={!canContact||Boolean(busy)} onClick={()=>quote(offer.id)} className="rounded-lg bg-[#2377ff] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busy===`quote:${offer.id}`?'Preparing…':'Prepare buyer quote'}</button>}</div></div>})}{!offers.length&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-3 text-xs leading-5 text-slate-500">No supplier option recorded yet. Add the best genuine source found for this buyer request.</div>}</div>
  {!quoteId&&<form onSubmit={submit} className="mt-4 grid gap-2 sm:grid-cols-2"><input name="title" required defaultValue={productQuery} className="app-input" placeholder="Product found"/><select name="vendor_id" className="app-input" defaultValue=""><option value="">Supplier not yet in vendor list</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}{v.status?` · ${v.status}`:''}</option>)}</select><input name="supplier_name" className="app-input" placeholder="Supplier/source name"/><input name="source_url" type="url" className="app-input" placeholder="Supplier/product URL (optional)"/><input name="source_price" required type="number" min="0" step="0.01" className="app-input" placeholder="Our cost (₦)"/><input name="selling_price" required type="number" min="0" step="0.01" className="app-input" placeholder="Selling price (₦)"/><select name="availability" className="app-input" defaultValue="available"><option value="available">Available</option><option value="limited">Limited</option><option value="preorder">Pre-order</option><option value="unconfirmed">Unconfirmed</option></select><input name="notes" className="app-input" placeholder="Sourcing notes"/><button disabled={Boolean(busy)} className="primary-button sm:col-span-2">{busy==='offer'?'Saving…':'Save sourcing option'}</button></form>}
  {!canContact&&!quoteId&&<div className="mt-3 text-xs font-semibold text-amber-700">Buyer contact consent is required before preparing a direct quotation.</div>}{message&&<div className="mt-3 text-xs font-bold text-slate-700">{message}</div>}
 </div>;
}
