'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function DealQuickCreate({leads,staff}:{leads:any[];staff:any[]}){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);const payload={title:fd.get('title'),lead_id:fd.get('lead_id')||null,owner_id:fd.get('owner_id')||null,amount:Number(fd.get('amount')||0),probability:Number(fd.get('probability')||25),expected_close_at:fd.get('expected_close_at')||null};const res=await fetch('/api/deals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await res.json();setBusy(false);if(!res.ok){setError(body.error||'Could not create deal');return;}e.currentTarget.reset();router.refresh();}
 return <form onSubmit={submit} className="quick-grid deal-create-grid"><input name="title" required placeholder="Deal / opportunity name" className="app-input"/><select name="lead_id" className="app-input" defaultValue=""><option value="">No linked lead</option>{leads.map((l:any)=><option key={l.id} value={l.id}>{l.name||l.phone||l.email||'Unnamed lead'}</option>)}</select><select name="owner_id" className="app-input" defaultValue=""><option value="">Auto / me</option>{staff.map((s:any)=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select><input name="amount" type="number" min="0" step="0.01" placeholder="Deal value" className="app-input"/><select name="probability" className="app-input" defaultValue="25"><option value="25">25% likely</option><option value="50">50% likely</option><option value="75">75% likely</option><option value="90">90% likely</option></select><input name="expected_close_at" type="datetime-local" className="app-input"/><button disabled={busy} className="primary-button">{busy?'Creating…':'Create deal'}</button>{error&&<div className="form-error">{error}</div>}</form>
}
