import {NextResponse} from 'next/server';
import {requireUser} from '@/lib/auth';
import {matchProducts,scoreBuyerIntent,canContactBuyer} from '@/lib/buyers/intelligence';

async function productsFor(supabase:any,org:string){const {data}=await supabase.from('connected_products').select('id,external_product_id,name,category,price,stock_quantity,active,sku,metadata').eq('organization_id',org).eq('active',true).limit(500);return data??[];}

export async function GET(){const {supabase,user,profile}=await requireUser();if(!user||!profile)return NextResponse.json({error:'Unauthorized'},{status:401});const {data,error}=await supabase.from('buyer_intents').select('*,assignee:profiles!buyer_intents_assigned_to_fkey(id,full_name)').eq('organization_id',profile.organization_id).order('intent_score',{ascending:false}).order('observed_at',{ascending:false}).limit(250);return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({data});}

export async function POST(req:Request){const {supabase,user,profile}=await requireUser();if(!user||!profile)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json();if(!b.product_query)return NextResponse.json({error:'product_query is required'},{status:400});const input={product_query:b.product_query,category:b.category||null,brand:b.brand||null,model:b.model||null,budget_min:b.budget_min?Number(b.budget_min):null,budget_max:b.budget_max?Number(b.budget_max):null,state:b.state||null,city:b.city||null,urgency:b.urgency||'normal',source:b.source||'manual',consent_status:b.consent_status||'unknown'};const products=await productsFor(supabase,profile.organization_id);const matches=matchProducts(input,products);const score=scoreBuyerIntent(input);
 const {data,error}=await supabase.from('buyer_intents').insert({organization_id:profile.organization_id,source:input.source,buyer_name:b.buyer_name||null,phone:b.phone||null,email:b.email||null,product_query:input.product_query,category:input.category,brand:input.brand,model:input.model,budget_min:input.budget_min,budget_max:input.budget_max,state:input.state,city:input.city,urgency:input.urgency,consent_status:input.consent_status,intent_score:score,matched_products:matches,evidence:b.evidence??{capture:'manual'}}).select().single();if(error)return NextResponse.json({error:error.message},{status:400});await supabase.from('activity_logs').insert({organization_id:profile.organization_id,actor_id:user.id,action:'buyer_intent.created',entity_type:'buyer_intent',entity_id:data.id,metadata:{source:input.source,score,match_count:matches.length}});return NextResponse.json({data},{status:201});}

export async function PATCH(req:Request){const {supabase,user,profile}=await requireUser();if(!user||!profile)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json();if(!b.id||!b.action)return NextResponse.json({error:'id and action are required'},{status:400});const {data:intent,error:e}=await supabase.from('buyer_intents').select('*').eq('id',b.id).eq('organization_id',profile.organization_id).single();if(e||!intent)return NextResponse.json({error:'Buyer intent not found'},{status:404});
 if(b.action==='refresh_match'){const products=await productsFor(supabase,profile.organization_id);const matches=matchProducts(intent,products);const score=scoreBuyerIntent(intent);const {data,error}=await supabase.from('buyer_intents').update({matched_products:matches,intent_score:score,status:matches.length?'matched':intent.status,updated_at:new Date().toISOString()}).eq('id',intent.id).select().single();return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({data});}
 if(b.action==='convert_to_lead'){if(!canContactBuyer(intent.consent_status))return NextResponse.json({error:'Buyer has not opted in to direct contact'},{status:409});if(intent.lead_id)return NextResponse.json({data:{lead_id:intent.lead_id}});const {data:lead,error}=await supabase.from('leads').insert({organization_id:profile.organization_id,name:intent.buyer_name||intent.phone||'Buyer opportunity',phone:intent.phone,email:intent.email,source:intent.source,product_interest:intent.product_query,status:'new',assigned_to:intent.assigned_to,estimated_value:intent.budget_max,notes:`Buyer intelligence score ${intent.intent_score}. ${intent.city||''} ${intent.state||''}`.trim()}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:400});await supabase.from('buyer_intents').update({lead_id:lead.id,status:'converted',updated_at:new Date().toISOString()}).eq('id',intent.id);await supabase.from('lead_activities').insert({lead_id:lead.id,actor_id:user.id,activity_type:'created_from_buyer_intent',notes:`Converted from buyer intent ${intent.id}`});return NextResponse.json({data:{lead_id:lead.id}});}
 if(b.action==='close'){const {error}=await supabase.from('buyer_intents').update({status:'closed',updated_at:new Date().toISOString()}).eq('id',intent.id);return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true});}
 return NextResponse.json({error:'Unsupported action'},{status:400});}
