import {NextResponse} from 'next/server';import {requireUser,canManage} from '@/lib/auth';
export async function POST(req:Request){const {supabase,user,profile}=await requireUser();if(!user||!profile)return NextResponse.json({error:'Unauthorized'},{status:401});if(!canManage(profile.role))return NextResponse.json({error:'Forbidden'},{status:403});const b=await req.json();if(b.action==='scan'){
 const now=new Date(); const {data:rules}=await supabase.from('sla_rules').select('*').eq('organization_id',profile.organization_id).eq('active',true); let created=0;
 for(const r of rules||[]){ if(r.entity_type==='lead'){const cutoff=new Date(now.getTime()-r.response_minutes*60000).toISOString();let q=supabase.from('leads').select('id,source,assigned_to,created_at,last_contacted_at,status').eq('organization_id',profile.organization_id).lt('created_at',cutoff).is('last_contacted_at',null);if(r.source)q=q.eq('source',r.source);const {data:rows}=await q;for(const x of rows||[]){const due=new Date(new Date(x.created_at).getTime()+r.response_minutes*60000).toISOString();const {error}=await supabase.from('sla_incidents').upsert({organization_id:profile.organization_id,sla_rule_id:r.id,entity_type:'lead',entity_id:x.id,source:x.source,due_at:due,status:new Date(due)<now?'breached':'open',assigned_to:x.assigned_to,escalation_level:new Date(due)<now?1:0,updated_at:now.toISOString()},{onConflict:'organization_id,entity_type,entity_id,sla_rule_id'});if(!error)created++}}
 }
 await supabase.from('activity_logs').insert({organization_id:profile.organization_id,actor_id:user.id,action:'sla.scan',entity_type:'sla',metadata:{incidents_processed:created}});return NextResponse.json({data:{processed:created}})
 }
 if(b.action==='resolve'&&b.id){const {data,error}=await supabase.from('sla_incidents').update({status:'resolved',resolved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',b.id).eq('organization_id',profile.organization_id).select().single();return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({data})}
 return NextResponse.json({error:'Unsupported action'},{status:400})}
