-- Applied to the live WorkflowOS Supabase project on 2026-08-11.
-- Growth recommendations are generated by trusted WorkflowOS server-side intelligence.
-- Browser users may read them and use the existing action API to update only lifecycle
-- fields. They may not manufacture recommendations or rewrite scores/evidence directly.

drop policy if exists "org growth recommendations" on public.growth_recommendations;
drop policy if exists "growth recommendations select same org" on public.growth_recommendations;
drop policy if exists "growth recommendations update lifecycle" on public.growth_recommendations;

create policy "growth recommendations select same org"
on public.growth_recommendations
for select
to authenticated
using (organization_id = public.current_org_id());

create policy "growth recommendations update lifecycle"
on public.growth_recommendations
for update
to authenticated
using (organization_id = public.current_org_id())
with check (organization_id = public.current_org_id());

revoke all privileges on table public.growth_recommendations from anon;
revoke insert, delete, update, truncate, references, trigger on table public.growth_recommendations from authenticated;

grant select on table public.growth_recommendations to authenticated;
grant update (status, created_task_id, updated_at) on table public.growth_recommendations to authenticated;
