import Link from 'next/link';
import { redirect } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import WorkspaceShell from '@/components/WorkspaceShell';

const nav=[['Today','/today'],['Buyer Radar','/buyers/radar'],['Opportunity Center','/opportunities'],['Tasks','/tasks'],['Campaigns','/campaigns'],['Automations','/automations'],['Marketing','/marketing'],['Leads','/leads'],['Sites','/sites'],['Catalog','/catalog'],['Vendors','/vendors'],['Marketplaces','/marketplaces'],['Marketplace Jobs','/marketplace-jobs'],['Integrations','/integrations'],['Team','/team'],['AI Assistant','/ai']];
export default async function Dashboard(){
 const {supabase,user,profile}=await requireUser(); if(!user||!profile) redirect('/login'); const org=profile.organization_id;
 const [recQ,campQ,leadQ,taskQ,topQ]=await Promise.all([
  supabase.from('growth_recommendations').select('id',{count:'exact',head:true}).eq('organization_id',org).eq('status','new'),
  supabase.from('campaigns').select('id',{count:'exact',head:true}).eq('organization_id',org).eq('status','active'),
  supabase.from('leads').select('id',{count:'exact',head:true}).eq('organization_id',org).in('status',['new','contacted','interested','negotiating']),
  supabase.from('tasks').select('id',{count:'exact',head:true}).eq('organization_id',org).lt('due_at',new Date().toISOString()).not('status','in','("completed","approved","cancelled")'),
  supabase.from('growth_recommendations').select('id,title,rationale,score,status').eq('organization_id',org).eq('status','new').order('score',{ascending:false}).limit(4)
 ]);
 const cards=[['Growth opportunities',String(recQ.count??0),'Needs review'],['Active campaigns',String(campQ.count??0),'Running now'],['Open leads',String(leadQ.count??0),'Sales pipeline'],['Overdue tasks',String(taskQ.count??0),'Review today']];
 return <WorkspaceShell title="Dashboard" subtitle="Growth, execution and connected commerce" profile={profile}><div className="mx-auto max-w-7xl px-6 py-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-sm font-semibold uppercase tracking-[.2em] text-slate-500">WorkflowOS V1.1</div><h1 className="mt-2 text-3xl font-bold">Work that turns into growth.</h1><p className="mt-2 text-slate-600">Coordinate people, campaigns, leads and external business signals.</p></div><span className="rounded-full bg-slate-900 px-4 py-2 text-sm font-semibold text-white">GadgetPoint: bridge-ready</span></div><section className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{cards.map(([title,value,note])=><div className="rounded-3xl border bg-white p-5 shadow-sm" key={title}><div className="text-sm text-slate-500">{title}</div><div className="mt-2 text-3xl font-bold">{value}</div><div className="mt-2 text-xs text-slate-500">{note}</div></div>)}</section><section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">What should we do today?</h2><Link href="/opportunities" className="text-sm font-semibold">View all →</Link></div><div className="mt-5 space-y-3">{(topQ.data??[]).map((r:any)=><div key={r.id} className="flex items-center gap-4 rounded-2xl border p-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-900 text-sm font-bold text-white">{Number(r.score).toFixed(0)}</div><div className="min-w-0 flex-1"><div className="font-medium">{r.title}</div><div className="mt-1 truncate text-sm text-slate-500">{r.rationale||'Recommended action available'}</div></div></div>)}{!topQ.data?.length&&<div className="rounded-2xl border border-dashed p-6 text-sm text-slate-500">No live recommendations yet.</div>}</div></div><div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Open a workspace</h2><div className="mt-4 grid grid-cols-2 gap-3">{nav.map(([label,href])=><Link className="rounded-2xl border p-4 text-sm font-medium hover:bg-slate-50" href={href} key={href}>{label}</Link>)}</div></div></section></div></WorkspaceShell>;
}
